name: CI/CD to EC2_Instnace 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t wanderlust-app ./app

      - name: Tag Image
        run: |
          docker tag wanderlust-app:latest \
          ${{ steps.login-ecr.outputs.registry }}/wanderlust-app:latest

      - name: Push Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/wanderlust-app:latest

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy on EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF

          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

          docker pull ${{ steps.login-ecr.outputs.registry }}/wanderlust-app:latest

          docker stop wanderlust-app || true
          docker rm wanderlust-app || true

          docker run -d -p 80:3000 --name wanderlust-app --restart always ${{ steps.login-ecr.outputs.registry }}/wanderlust-app:latest

          EOF

      
